// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package codec_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewBase64CoderMock creates a new instance of Base64CoderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBase64CoderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Base64CoderMock {
	mock := &Base64CoderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Base64CoderMock is an autogenerated mock type for the Base64Coder type
type Base64CoderMock struct {
	mock.Mock
}

type Base64CoderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *Base64CoderMock) EXPECT() *Base64CoderMock_Expecter {
	return &Base64CoderMock_Expecter{mock: &_m.Mock}
}

// DecodeBase64 provides a mock function for the type Base64CoderMock
func (_mock *Base64CoderMock) DecodeBase64(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DecodeBase64")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Base64CoderMock_DecodeBase64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeBase64'
type Base64CoderMock_DecodeBase64_Call struct {
	*mock.Call
}

// DecodeBase64 is a helper method to define mock.On call
//   - s string
func (_e *Base64CoderMock_Expecter) DecodeBase64(s interface{}) *Base64CoderMock_DecodeBase64_Call {
	return &Base64CoderMock_DecodeBase64_Call{Call: _e.mock.On("DecodeBase64", s)}
}

func (_c *Base64CoderMock_DecodeBase64_Call) Run(run func(s string)) *Base64CoderMock_DecodeBase64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Base64CoderMock_DecodeBase64_Call) Return(s1 string, err error) *Base64CoderMock_DecodeBase64_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *Base64CoderMock_DecodeBase64_Call) RunAndReturn(run func(s string) (string, error)) *Base64CoderMock_DecodeBase64_Call {
	_c.Call.Return(run)
	return _c
}

// EncodeBase64 provides a mock function for the type Base64CoderMock
func (_mock *Base64CoderMock) EncodeBase64(s string) string {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for EncodeBase64")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Base64CoderMock_EncodeBase64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeBase64'
type Base64CoderMock_EncodeBase64_Call struct {
	*mock.Call
}

// EncodeBase64 is a helper method to define mock.On call
//   - s string
func (_e *Base64CoderMock_Expecter) EncodeBase64(s interface{}) *Base64CoderMock_EncodeBase64_Call {
	return &Base64CoderMock_EncodeBase64_Call{Call: _e.mock.On("EncodeBase64", s)}
}

func (_c *Base64CoderMock_EncodeBase64_Call) Run(run func(s string)) *Base64CoderMock_EncodeBase64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Base64CoderMock_EncodeBase64_Call) Return(s1 string) *Base64CoderMock_EncodeBase64_Call {
	_c.Call.Return(s1)
	return _c
}

func (_c *Base64CoderMock_EncodeBase64_Call) RunAndReturn(run func(s string) string) *Base64CoderMock_EncodeBase64_Call {
	_c.Call.Return(run)
	return _c
}

// NewJSONCoderMock creates a new instance of JSONCoderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJSONCoderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JSONCoderMock {
	mock := &JSONCoderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JSONCoderMock is an autogenerated mock type for the JSONCoder type
type JSONCoderMock struct {
	mock.Mock
}

type JSONCoderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JSONCoderMock) EXPECT() *JSONCoderMock_Expecter {
	return &JSONCoderMock_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function for the type JSONCoderMock
func (_mock *JSONCoderMock) Marshal(v any) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(any) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JSONCoderMock_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type JSONCoderMock_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v any
func (_e *JSONCoderMock_Expecter) Marshal(v interface{}) *JSONCoderMock_Marshal_Call {
	return &JSONCoderMock_Marshal_Call{Call: _e.mock.On("Marshal", v)}
}

func (_c *JSONCoderMock_Marshal_Call) Run(run func(v any)) *JSONCoderMock_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JSONCoderMock_Marshal_Call) Return(bytes []byte, err error) *JSONCoderMock_Marshal_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *JSONCoderMock_Marshal_Call) RunAndReturn(run func(v any) ([]byte, error)) *JSONCoderMock_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type JSONCoderMock
func (_mock *JSONCoderMock) Unmarshal(data []byte, v any) error {
	ret := _mock.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, any) error); ok {
		r0 = returnFunc(data, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JSONCoderMock_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type JSONCoderMock_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
//   - v any
func (_e *JSONCoderMock_Expecter) Unmarshal(data interface{}, v interface{}) *JSONCoderMock_Unmarshal_Call {
	return &JSONCoderMock_Unmarshal_Call{Call: _e.mock.On("Unmarshal", data, v)}
}

func (_c *JSONCoderMock_Unmarshal_Call) Run(run func(data []byte, v any)) *JSONCoderMock_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JSONCoderMock_Unmarshal_Call) Return(err error) *JSONCoderMock_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JSONCoderMock_Unmarshal_Call) RunAndReturn(run func(data []byte, v any) error) *JSONCoderMock_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}
