// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hash_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHashManagerMock creates a new instance of HashManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashManagerMock {
	mock := &HashManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HashManagerMock is an autogenerated mock type for the HashManager type
type HashManagerMock struct {
	mock.Mock
}

type HashManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HashManagerMock) EXPECT() *HashManagerMock_Expecter {
	return &HashManagerMock_Expecter{mock: &_m.Mock}
}

// GenerateSalt provides a mock function for the type HashManagerMock
func (_mock *HashManagerMock) GenerateSalt() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateSalt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HashManagerMock_GenerateSalt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSalt'
type HashManagerMock_GenerateSalt_Call struct {
	*mock.Call
}

// GenerateSalt is a helper method to define mock.On call
func (_e *HashManagerMock_Expecter) GenerateSalt() *HashManagerMock_GenerateSalt_Call {
	return &HashManagerMock_GenerateSalt_Call{Call: _e.mock.On("GenerateSalt")}
}

func (_c *HashManagerMock_GenerateSalt_Call) Run(run func()) *HashManagerMock_GenerateSalt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HashManagerMock_GenerateSalt_Call) Return(s string, err error) *HashManagerMock_GenerateSalt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *HashManagerMock_GenerateSalt_Call) RunAndReturn(run func() (string, error)) *HashManagerMock_GenerateSalt_Call {
	_c.Call.Return(run)
	return _c
}

// HashSha256Encode provides a mock function for the type HashManagerMock
func (_mock *HashManagerMock) HashSha256Encode(plainText string) string {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for HashSha256Encode")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HashManagerMock_HashSha256Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashSha256Encode'
type HashManagerMock_HashSha256Encode_Call struct {
	*mock.Call
}

// HashSha256Encode is a helper method to define mock.On call
//   - plainText string
func (_e *HashManagerMock_Expecter) HashSha256Encode(plainText interface{}) *HashManagerMock_HashSha256Encode_Call {
	return &HashManagerMock_HashSha256Encode_Call{Call: _e.mock.On("HashSha256Encode", plainText)}
}

func (_c *HashManagerMock_HashSha256Encode_Call) Run(run func(plainText string)) *HashManagerMock_HashSha256Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HashManagerMock_HashSha256Encode_Call) Return(s string) *HashManagerMock_HashSha256Encode_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HashManagerMock_HashSha256Encode_Call) RunAndReturn(run func(plainText string) string) *HashManagerMock_HashSha256Encode_Call {
	_c.Call.Return(run)
	return _c
}

// HashSha256EncodePepper provides a mock function for the type HashManagerMock
func (_mock *HashManagerMock) HashSha256EncodePepper(plainText string) string {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for HashSha256EncodePepper")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HashManagerMock_HashSha256EncodePepper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashSha256EncodePepper'
type HashManagerMock_HashSha256EncodePepper_Call struct {
	*mock.Call
}

// HashSha256EncodePepper is a helper method to define mock.On call
//   - plainText string
func (_e *HashManagerMock_Expecter) HashSha256EncodePepper(plainText interface{}) *HashManagerMock_HashSha256EncodePepper_Call {
	return &HashManagerMock_HashSha256EncodePepper_Call{Call: _e.mock.On("HashSha256EncodePepper", plainText)}
}

func (_c *HashManagerMock_HashSha256EncodePepper_Call) Run(run func(plainText string)) *HashManagerMock_HashSha256EncodePepper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HashManagerMock_HashSha256EncodePepper_Call) Return(s string) *HashManagerMock_HashSha256EncodePepper_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HashManagerMock_HashSha256EncodePepper_Call) RunAndReturn(run func(plainText string) string) *HashManagerMock_HashSha256EncodePepper_Call {
	_c.Call.Return(run)
	return _c
}

// HashSha256EncodeSalt provides a mock function for the type HashManagerMock
func (_mock *HashManagerMock) HashSha256EncodeSalt(plainText string, salt string) string {
	ret := _mock.Called(plainText, salt)

	if len(ret) == 0 {
		panic("no return value specified for HashSha256EncodeSalt")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(plainText, salt)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HashManagerMock_HashSha256EncodeSalt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashSha256EncodeSalt'
type HashManagerMock_HashSha256EncodeSalt_Call struct {
	*mock.Call
}

// HashSha256EncodeSalt is a helper method to define mock.On call
//   - plainText string
//   - salt string
func (_e *HashManagerMock_Expecter) HashSha256EncodeSalt(plainText interface{}, salt interface{}) *HashManagerMock_HashSha256EncodeSalt_Call {
	return &HashManagerMock_HashSha256EncodeSalt_Call{Call: _e.mock.On("HashSha256EncodeSalt", plainText, salt)}
}

func (_c *HashManagerMock_HashSha256EncodeSalt_Call) Run(run func(plainText string, salt string)) *HashManagerMock_HashSha256EncodeSalt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HashManagerMock_HashSha256EncodeSalt_Call) Return(s string) *HashManagerMock_HashSha256EncodeSalt_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HashManagerMock_HashSha256EncodeSalt_Call) RunAndReturn(run func(plainText string, salt string) string) *HashManagerMock_HashSha256EncodeSalt_Call {
	_c.Call.Return(run)
	return _c
}
