// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sftp_mocks

import (
	"context"
	"io"
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ClientMock
func (_mock *ClientMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClientMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ClientMock_Expecter) Close() *ClientMock_Close_Call {
	return &ClientMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ClientMock_Close_Call) Run(run func()) *ClientMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientMock_Close_Call) Return(err error) *ClientMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Close_Call) RunAndReturn(run func() error) *ClientMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ClientMock
func (_mock *ClientMock) Delete(ctx context.Context, remotePath string) error {
	ret := _mock.Called(ctx, remotePath)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, remotePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClientMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - remotePath string
func (_e *ClientMock_Expecter) Delete(ctx interface{}, remotePath interface{}) *ClientMock_Delete_Call {
	return &ClientMock_Delete_Call{Call: _e.mock.On("Delete", ctx, remotePath)}
}

func (_c *ClientMock_Delete_Call) Run(run func(ctx context.Context, remotePath string)) *ClientMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientMock_Delete_Call) Return(err error) *ClientMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Delete_Call) RunAndReturn(run func(ctx context.Context, remotePath string) error) *ClientMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type ClientMock
func (_mock *ClientMock) Download(ctx context.Context, remotePath string, out io.Writer) error {
	ret := _mock.Called(ctx, remotePath, out)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, remotePath, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type ClientMock_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - remotePath string
//   - out io.Writer
func (_e *ClientMock_Expecter) Download(ctx interface{}, remotePath interface{}, out interface{}) *ClientMock_Download_Call {
	return &ClientMock_Download_Call{Call: _e.mock.On("Download", ctx, remotePath, out)}
}

func (_c *ClientMock_Download_Call) Run(run func(ctx context.Context, remotePath string, out io.Writer)) *ClientMock_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientMock_Download_Call) Return(err error) *ClientMock_Download_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Download_Call) RunAndReturn(run func(ctx context.Context, remotePath string, out io.Writer) error) *ClientMock_Download_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirectory provides a mock function for the type ClientMock
func (_mock *ClientMock) ListDirectory(ctx context.Context, remotePath string) ([]os.FileInfo, error) {
	ret := _mock.Called(ctx, remotePath)

	if len(ret) == 0 {
		panic("no return value specified for ListDirectory")
	}

	var r0 []os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]os.FileInfo, error)); ok {
		return returnFunc(ctx, remotePath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []os.FileInfo); ok {
		r0 = returnFunc(ctx, remotePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, remotePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_ListDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirectory'
type ClientMock_ListDirectory_Call struct {
	*mock.Call
}

// ListDirectory is a helper method to define mock.On call
//   - ctx context.Context
//   - remotePath string
func (_e *ClientMock_Expecter) ListDirectory(ctx interface{}, remotePath interface{}) *ClientMock_ListDirectory_Call {
	return &ClientMock_ListDirectory_Call{Call: _e.mock.On("ListDirectory", ctx, remotePath)}
}

func (_c *ClientMock_ListDirectory_Call) Run(run func(ctx context.Context, remotePath string)) *ClientMock_ListDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientMock_ListDirectory_Call) Return(vs []os.FileInfo, err error) *ClientMock_ListDirectory_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *ClientMock_ListDirectory_Call) RunAndReturn(run func(ctx context.Context, remotePath string) ([]os.FileInfo, error)) *ClientMock_ListDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type ClientMock
func (_mock *ClientMock) Upload(ctx context.Context, remotePath string, content io.Reader) error {
	ret := _mock.Called(ctx, remotePath, content)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = returnFunc(ctx, remotePath, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type ClientMock_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - remotePath string
//   - content io.Reader
func (_e *ClientMock_Expecter) Upload(ctx interface{}, remotePath interface{}, content interface{}) *ClientMock_Upload_Call {
	return &ClientMock_Upload_Call{Call: _e.mock.On("Upload", ctx, remotePath, content)}
}

func (_c *ClientMock_Upload_Call) Run(run func(ctx context.Context, remotePath string, content io.Reader)) *ClientMock_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientMock_Upload_Call) Return(err error) *ClientMock_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Upload_Call) RunAndReturn(run func(ctx context.Context, remotePath string, content io.Reader) error) *ClientMock_Upload_Call {
	_c.Call.Return(run)
	return _c
}
