// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clock_mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewClockMock creates a new instance of ClockMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClockMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClockMock {
	mock := &ClockMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClockMock is an autogenerated mock type for the Clock type
type ClockMock struct {
	mock.Mock
}

type ClockMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClockMock) EXPECT() *ClockMock_Expecter {
	return &ClockMock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type ClockMock
func (_mock *ClockMock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// ClockMock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type ClockMock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *ClockMock_Expecter) Now() *ClockMock_Now_Call {
	return &ClockMock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *ClockMock_Now_Call) Run(run func()) *ClockMock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClockMock_Now_Call) Return(time1 time.Time) *ClockMock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *ClockMock_Now_Call) RunAndReturn(run func() time.Time) *ClockMock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NowIn provides a mock function for the type ClockMock
func (_mock *ClockMock) NowIn(location string) (time.Time, error) {
	ret := _mock.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for NowIn")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (time.Time, error)); ok {
		return returnFunc(location)
	}
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(location)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClockMock_NowIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NowIn'
type ClockMock_NowIn_Call struct {
	*mock.Call
}

// NowIn is a helper method to define mock.On call
//   - location string
func (_e *ClockMock_Expecter) NowIn(location interface{}) *ClockMock_NowIn_Call {
	return &ClockMock_NowIn_Call{Call: _e.mock.On("NowIn", location)}
}

func (_c *ClockMock_NowIn_Call) Run(run func(location string)) *ClockMock_NowIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClockMock_NowIn_Call) Return(time1 time.Time, err error) *ClockMock_NowIn_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *ClockMock_NowIn_Call) RunAndReturn(run func(location string) (time.Time, error)) *ClockMock_NowIn_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type ClockMock
func (_mock *ClockMock) Parse(layout string, value string) (time.Time, error) {
	ret := _mock.Called(layout, value)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (time.Time, error)); ok {
		return returnFunc(layout, value)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) time.Time); ok {
		r0 = returnFunc(layout, value)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(layout, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClockMock_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type ClockMock_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - layout string
//   - value string
func (_e *ClockMock_Expecter) Parse(layout interface{}, value interface{}) *ClockMock_Parse_Call {
	return &ClockMock_Parse_Call{Call: _e.mock.On("Parse", layout, value)}
}

func (_c *ClockMock_Parse_Call) Run(run func(layout string, value string)) *ClockMock_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClockMock_Parse_Call) Return(time1 time.Time, err error) *ClockMock_Parse_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *ClockMock_Parse_Call) RunAndReturn(run func(layout string, value string) (time.Time, error)) *ClockMock_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ParseIn provides a mock function for the type ClockMock
func (_mock *ClockMock) ParseIn(layout string, value string, location string) (time.Time, error) {
	ret := _mock.Called(layout, value, location)

	if len(ret) == 0 {
		panic("no return value specified for ParseIn")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (time.Time, error)); ok {
		return returnFunc(layout, value, location)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) time.Time); ok {
		r0 = returnFunc(layout, value, location)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(layout, value, location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClockMock_ParseIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseIn'
type ClockMock_ParseIn_Call struct {
	*mock.Call
}

// ParseIn is a helper method to define mock.On call
//   - layout string
//   - value string
//   - location string
func (_e *ClockMock_Expecter) ParseIn(layout interface{}, value interface{}, location interface{}) *ClockMock_ParseIn_Call {
	return &ClockMock_ParseIn_Call{Call: _e.mock.On("ParseIn", layout, value, location)}
}

func (_c *ClockMock_ParseIn_Call) Run(run func(layout string, value string, location string)) *ClockMock_ParseIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClockMock_ParseIn_Call) Return(time1 time.Time, err error) *ClockMock_ParseIn_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *ClockMock_ParseIn_Call) RunAndReturn(run func(layout string, value string, location string) (time.Time, error)) *ClockMock_ParseIn_Call {
	_c.Call.Return(run)
	return _c
}
