// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/b2c-e-commerce-platform/platform/backend/common/kafka"
)

// NewProducerMock creates a new instance of ProducerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerMock {
	mock := &ProducerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProducerMock is an autogenerated mock type for the Producer type
type ProducerMock struct {
	mock.Mock
}

type ProducerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProducerMock) EXPECT() *ProducerMock_Expecter {
	return &ProducerMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ProducerMock
func (_mock *ProducerMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProducerMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ProducerMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ProducerMock_Expecter) Close() *ProducerMock_Close_Call {
	return &ProducerMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ProducerMock_Close_Call) Run(run func()) *ProducerMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProducerMock_Close_Call) Return(err error) *ProducerMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProducerMock_Close_Call) RunAndReturn(run func() error) *ProducerMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type ProducerMock
func (_mock *ProducerMock) SendMessage(ctx context.Context, topic string, message any) error {
	ret := _mock.Called(ctx, topic, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, topic, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProducerMock_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type ProducerMock_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - message any
func (_e *ProducerMock_Expecter) SendMessage(ctx interface{}, topic interface{}, message interface{}) *ProducerMock_SendMessage_Call {
	return &ProducerMock_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, topic, message)}
}

func (_c *ProducerMock_SendMessage_Call) Run(run func(ctx context.Context, topic string, message any)) *ProducerMock_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProducerMock_SendMessage_Call) Return(err error) *ProducerMock_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProducerMock_SendMessage_Call) RunAndReturn(run func(ctx context.Context, topic string, message any) error) *ProducerMock_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageWithOption provides a mock function for the type ProducerMock
func (_mock *ProducerMock) SendMessageWithOption(ctx context.Context, topic string, message any, option kafka.SendMessageOption) error {
	ret := _mock.Called(ctx, topic, message, option)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithOption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, kafka.SendMessageOption) error); ok {
		r0 = returnFunc(ctx, topic, message, option)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProducerMock_SendMessageWithOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageWithOption'
type ProducerMock_SendMessageWithOption_Call struct {
	*mock.Call
}

// SendMessageWithOption is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - message any
//   - option kafka.SendMessageOption
func (_e *ProducerMock_Expecter) SendMessageWithOption(ctx interface{}, topic interface{}, message interface{}, option interface{}) *ProducerMock_SendMessageWithOption_Call {
	return &ProducerMock_SendMessageWithOption_Call{Call: _e.mock.On("SendMessageWithOption", ctx, topic, message, option)}
}

func (_c *ProducerMock_SendMessageWithOption_Call) Run(run func(ctx context.Context, topic string, message any, option kafka.SendMessageOption)) *ProducerMock_SendMessageWithOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 kafka.SendMessageOption
		if args[3] != nil {
			arg3 = args[3].(kafka.SendMessageOption)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProducerMock_SendMessageWithOption_Call) Return(err error) *ProducerMock_SendMessageWithOption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProducerMock_SendMessageWithOption_Call) RunAndReturn(run func(ctx context.Context, topic string, message any, option kafka.SendMessageOption) error) *ProducerMock_SendMessageWithOption_Call {
	_c.Call.Return(run)
	return _c
}
