// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token_mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/b2c-e-commerce-platform/platform/backend/common/token"
)

// NewJWTSignerMock creates a new instance of JWTSignerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTSignerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTSignerMock {
	mock := &JWTSignerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JWTSignerMock is an autogenerated mock type for the JWTSigner type
type JWTSignerMock struct {
	mock.Mock
}

type JWTSignerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTSignerMock) EXPECT() *JWTSignerMock_Expecter {
	return &JWTSignerMock_Expecter{mock: &_m.Mock}
}

// SignES256 provides a mock function for the type JWTSignerMock
func (_mock *JWTSignerMock) SignES256(payload token.Claims) (string, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for SignES256")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(token.Claims) (string, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func(token.Claims) string); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(token.Claims) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWTSignerMock_SignES256_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignES256'
type JWTSignerMock_SignES256_Call struct {
	*mock.Call
}

// SignES256 is a helper method to define mock.On call
//   - payload token.Claims
func (_e *JWTSignerMock_Expecter) SignES256(payload interface{}) *JWTSignerMock_SignES256_Call {
	return &JWTSignerMock_SignES256_Call{Call: _e.mock.On("SignES256", payload)}
}

func (_c *JWTSignerMock_SignES256_Call) Run(run func(payload token.Claims)) *JWTSignerMock_SignES256_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 token.Claims
		if args[0] != nil {
			arg0 = args[0].(token.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTSignerMock_SignES256_Call) Return(s string, err error) *JWTSignerMock_SignES256_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JWTSignerMock_SignES256_Call) RunAndReturn(run func(payload token.Claims) (string, error)) *JWTSignerMock_SignES256_Call {
	_c.Call.Return(run)
	return _c
}

// SignRS256 provides a mock function for the type JWTSignerMock
func (_mock *JWTSignerMock) SignRS256(payload token.Claims) (string, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for SignRS256")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(token.Claims) (string, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func(token.Claims) string); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(token.Claims) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWTSignerMock_SignRS256_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignRS256'
type JWTSignerMock_SignRS256_Call struct {
	*mock.Call
}

// SignRS256 is a helper method to define mock.On call
//   - payload token.Claims
func (_e *JWTSignerMock_Expecter) SignRS256(payload interface{}) *JWTSignerMock_SignRS256_Call {
	return &JWTSignerMock_SignRS256_Call{Call: _e.mock.On("SignRS256", payload)}
}

func (_c *JWTSignerMock_SignRS256_Call) Run(run func(payload token.Claims)) *JWTSignerMock_SignRS256_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 token.Claims
		if args[0] != nil {
			arg0 = args[0].(token.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTSignerMock_SignRS256_Call) Return(s string, err error) *JWTSignerMock_SignRS256_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JWTSignerMock_SignRS256_Call) RunAndReturn(run func(payload token.Claims) (string, error)) *JWTSignerMock_SignRS256_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTVerifierMock creates a new instance of JWTVerifierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTVerifierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTVerifierMock {
	mock := &JWTVerifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JWTVerifierMock is an autogenerated mock type for the JWTVerifier type
type JWTVerifierMock struct {
	mock.Mock
}

type JWTVerifierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTVerifierMock) EXPECT() *JWTVerifierMock_Expecter {
	return &JWTVerifierMock_Expecter{mock: &_m.Mock}
}

// VerifySignatureES256 provides a mock function for the type JWTVerifierMock
func (_mock *JWTVerifierMock) VerifySignatureES256(token1 string) error {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignatureES256")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(token1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JWTVerifierMock_VerifySignatureES256_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySignatureES256'
type JWTVerifierMock_VerifySignatureES256_Call struct {
	*mock.Call
}

// VerifySignatureES256 is a helper method to define mock.On call
//   - token1 string
func (_e *JWTVerifierMock_Expecter) VerifySignatureES256(token1 interface{}) *JWTVerifierMock_VerifySignatureES256_Call {
	return &JWTVerifierMock_VerifySignatureES256_Call{Call: _e.mock.On("VerifySignatureES256", token1)}
}

func (_c *JWTVerifierMock_VerifySignatureES256_Call) Run(run func(token1 string)) *JWTVerifierMock_VerifySignatureES256_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTVerifierMock_VerifySignatureES256_Call) Return(err error) *JWTVerifierMock_VerifySignatureES256_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JWTVerifierMock_VerifySignatureES256_Call) RunAndReturn(run func(token1 string) error) *JWTVerifierMock_VerifySignatureES256_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySignatureHS512 provides a mock function for the type JWTVerifierMock
func (_mock *JWTVerifierMock) VerifySignatureHS512(token1 string) error {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignatureHS512")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(token1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JWTVerifierMock_VerifySignatureHS512_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySignatureHS512'
type JWTVerifierMock_VerifySignatureHS512_Call struct {
	*mock.Call
}

// VerifySignatureHS512 is a helper method to define mock.On call
//   - token1 string
func (_e *JWTVerifierMock_Expecter) VerifySignatureHS512(token1 interface{}) *JWTVerifierMock_VerifySignatureHS512_Call {
	return &JWTVerifierMock_VerifySignatureHS512_Call{Call: _e.mock.On("VerifySignatureHS512", token1)}
}

func (_c *JWTVerifierMock_VerifySignatureHS512_Call) Run(run func(token1 string)) *JWTVerifierMock_VerifySignatureHS512_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTVerifierMock_VerifySignatureHS512_Call) Return(err error) *JWTVerifierMock_VerifySignatureHS512_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JWTVerifierMock_VerifySignatureHS512_Call) RunAndReturn(run func(token1 string) error) *JWTVerifierMock_VerifySignatureHS512_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySignatureRS256 provides a mock function for the type JWTVerifierMock
func (_mock *JWTVerifierMock) VerifySignatureRS256(token1 string) error {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignatureRS256")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(token1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JWTVerifierMock_VerifySignatureRS256_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySignatureRS256'
type JWTVerifierMock_VerifySignatureRS256_Call struct {
	*mock.Call
}

// VerifySignatureRS256 is a helper method to define mock.On call
//   - token1 string
func (_e *JWTVerifierMock_Expecter) VerifySignatureRS256(token1 interface{}) *JWTVerifierMock_VerifySignatureRS256_Call {
	return &JWTVerifierMock_VerifySignatureRS256_Call{Call: _e.mock.On("VerifySignatureRS256", token1)}
}

func (_c *JWTVerifierMock_VerifySignatureRS256_Call) Run(run func(token1 string)) *JWTVerifierMock_VerifySignatureRS256_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTVerifierMock_VerifySignatureRS256_Call) Return(err error) *JWTVerifierMock_VerifySignatureRS256_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JWTVerifierMock_VerifySignatureRS256_Call) RunAndReturn(run func(token1 string) error) *JWTVerifierMock_VerifySignatureRS256_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTParserMock creates a new instance of JWTParserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTParserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTParserMock {
	mock := &JWTParserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JWTParserMock is an autogenerated mock type for the JWTParser type
type JWTParserMock struct {
	mock.Mock
}

type JWTParserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTParserMock) EXPECT() *JWTParserMock_Expecter {
	return &JWTParserMock_Expecter{mock: &_m.Mock}
}

// ParseToken provides a mock function for the type JWTParserMock
func (_mock *JWTParserMock) ParseToken(token1 string) (*token.Claims, error) {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *token.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*token.Claims, error)); ok {
		return returnFunc(token1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *token.Claims); ok {
		r0 = returnFunc(token1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWTParserMock_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type JWTParserMock_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token1 string
func (_e *JWTParserMock_Expecter) ParseToken(token1 interface{}) *JWTParserMock_ParseToken_Call {
	return &JWTParserMock_ParseToken_Call{Call: _e.mock.On("ParseToken", token1)}
}

func (_c *JWTParserMock_ParseToken_Call) Run(run func(token1 string)) *JWTParserMock_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTParserMock_ParseToken_Call) Return(claims *token.Claims, err error) *JWTParserMock_ParseToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *JWTParserMock_ParseToken_Call) RunAndReturn(run func(token1 string) (*token.Claims, error)) *JWTParserMock_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateClaims provides a mock function for the type JWTParserMock
func (_mock *JWTParserMock) ValidateClaims(payload *token.Claims) error {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for ValidateClaims")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*token.Claims) error); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JWTParserMock_ValidateClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateClaims'
type JWTParserMock_ValidateClaims_Call struct {
	*mock.Call
}

// ValidateClaims is a helper method to define mock.On call
//   - payload *token.Claims
func (_e *JWTParserMock_Expecter) ValidateClaims(payload interface{}) *JWTParserMock_ValidateClaims_Call {
	return &JWTParserMock_ValidateClaims_Call{Call: _e.mock.On("ValidateClaims", payload)}
}

func (_c *JWTParserMock_ValidateClaims_Call) Run(run func(payload *token.Claims)) *JWTParserMock_ValidateClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *token.Claims
		if args[0] != nil {
			arg0 = args[0].(*token.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTParserMock_ValidateClaims_Call) Return(err error) *JWTParserMock_ValidateClaims_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JWTParserMock_ValidateClaims_Call) RunAndReturn(run func(payload *token.Claims) error) *JWTParserMock_ValidateClaims_Call {
	_c.Call.Return(run)
	return _c
}
