// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package generator_mocks

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAppUUIDMock creates a new instance of AppUUIDMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppUUIDMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppUUIDMock {
	mock := &AppUUIDMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AppUUIDMock is an autogenerated mock type for the AppUUID type
type AppUUIDMock struct {
	mock.Mock
}

type AppUUIDMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AppUUIDMock) EXPECT() *AppUUIDMock_Expecter {
	return &AppUUIDMock_Expecter{mock: &_m.Mock}
}

// GenerateUUID provides a mock function for the type AppUUIDMock
func (_mock *AppUUIDMock) GenerateUUID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateUUID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// AppUUIDMock_GenerateUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUUID'
type AppUUIDMock_GenerateUUID_Call struct {
	*mock.Call
}

// GenerateUUID is a helper method to define mock.On call
func (_e *AppUUIDMock_Expecter) GenerateUUID() *AppUUIDMock_GenerateUUID_Call {
	return &AppUUIDMock_GenerateUUID_Call{Call: _e.mock.On("GenerateUUID")}
}

func (_c *AppUUIDMock_GenerateUUID_Call) Run(run func()) *AppUUIDMock_GenerateUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUUIDMock_GenerateUUID_Call) Return(s string) *AppUUIDMock_GenerateUUID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *AppUUIDMock_GenerateUUID_Call) RunAndReturn(run func() string) *AppUUIDMock_GenerateUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateUUIDTypeStrict provides a mock function for the type AppUUIDMock
func (_mock *AppUUIDMock) GenerateUUIDTypeStrict() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateUUIDTypeStrict")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// AppUUIDMock_GenerateUUIDTypeStrict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUUIDTypeStrict'
type AppUUIDMock_GenerateUUIDTypeStrict_Call struct {
	*mock.Call
}

// GenerateUUIDTypeStrict is a helper method to define mock.On call
func (_e *AppUUIDMock_Expecter) GenerateUUIDTypeStrict() *AppUUIDMock_GenerateUUIDTypeStrict_Call {
	return &AppUUIDMock_GenerateUUIDTypeStrict_Call{Call: _e.mock.On("GenerateUUIDTypeStrict")}
}

func (_c *AppUUIDMock_GenerateUUIDTypeStrict_Call) Run(run func()) *AppUUIDMock_GenerateUUIDTypeStrict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUUIDMock_GenerateUUIDTypeStrict_Call) Return(uUID uuid.UUID) *AppUUIDMock_GenerateUUIDTypeStrict_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *AppUUIDMock_GenerateUUIDTypeStrict_Call) RunAndReturn(run func() uuid.UUID) *AppUUIDMock_GenerateUUIDTypeStrict_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateUUIDV7 provides a mock function for the type AppUUIDMock
func (_mock *AppUUIDMock) GenerateUUIDV7() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateUUIDV7")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// AppUUIDMock_GenerateUUIDV7_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUUIDV7'
type AppUUIDMock_GenerateUUIDV7_Call struct {
	*mock.Call
}

// GenerateUUIDV7 is a helper method to define mock.On call
func (_e *AppUUIDMock_Expecter) GenerateUUIDV7() *AppUUIDMock_GenerateUUIDV7_Call {
	return &AppUUIDMock_GenerateUUIDV7_Call{Call: _e.mock.On("GenerateUUIDV7")}
}

func (_c *AppUUIDMock_GenerateUUIDV7_Call) Run(run func()) *AppUUIDMock_GenerateUUIDV7_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUUIDMock_GenerateUUIDV7_Call) Return(uUID uuid.UUID) *AppUUIDMock_GenerateUUIDV7_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *AppUUIDMock_GenerateUUIDV7_Call) RunAndReturn(run func() uuid.UUID) *AppUUIDMock_GenerateUUIDV7_Call {
	_c.Call.Return(run)
	return _c
}
