// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package crypt_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCipherMock creates a new instance of CipherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCipherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CipherMock {
	mock := &CipherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CipherMock is an autogenerated mock type for the Cipher type
type CipherMock struct {
	mock.Mock
}

type CipherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CipherMock) EXPECT() *CipherMock_Expecter {
	return &CipherMock_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type CipherMock
func (_mock *CipherMock) Decrypt(encodedPayload string) (string, error) {
	ret := _mock.Called(encodedPayload)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(encodedPayload)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(encodedPayload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(encodedPayload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherMock_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type CipherMock_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - encodedPayload string
func (_e *CipherMock_Expecter) Decrypt(encodedPayload interface{}) *CipherMock_Decrypt_Call {
	return &CipherMock_Decrypt_Call{Call: _e.mock.On("Decrypt", encodedPayload)}
}

func (_c *CipherMock_Decrypt_Call) Run(run func(encodedPayload string)) *CipherMock_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CipherMock_Decrypt_Call) Return(s string, err error) *CipherMock_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CipherMock_Decrypt_Call) RunAndReturn(run func(encodedPayload string) (string, error)) *CipherMock_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type CipherMock
func (_mock *CipherMock) Encrypt(plaintext string, iv []byte) (string, error) {
	ret := _mock.Called(plaintext, iv)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (string, error)); ok {
		return returnFunc(plaintext, iv)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) string); ok {
		r0 = returnFunc(plaintext, iv)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(plaintext, iv)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherMock_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type CipherMock_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
//   - iv []byte
func (_e *CipherMock_Expecter) Encrypt(plaintext interface{}, iv interface{}) *CipherMock_Encrypt_Call {
	return &CipherMock_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext, iv)}
}

func (_c *CipherMock_Encrypt_Call) Run(run func(plaintext string, iv []byte)) *CipherMock_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CipherMock_Encrypt_Call) Return(s string, err error) *CipherMock_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CipherMock_Encrypt_Call) RunAndReturn(run func(plaintext string, iv []byte) (string, error)) *CipherMock_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateIV provides a mock function for the type CipherMock
func (_mock *CipherMock) GenerateIV() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateIV")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherMock_GenerateIV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateIV'
type CipherMock_GenerateIV_Call struct {
	*mock.Call
}

// GenerateIV is a helper method to define mock.On call
func (_e *CipherMock_Expecter) GenerateIV() *CipherMock_GenerateIV_Call {
	return &CipherMock_GenerateIV_Call{Call: _e.mock.On("GenerateIV")}
}

func (_c *CipherMock_GenerateIV_Call) Run(run func()) *CipherMock_GenerateIV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CipherMock_GenerateIV_Call) Return(bytes []byte, err error) *CipherMock_GenerateIV_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *CipherMock_GenerateIV_Call) RunAndReturn(run func() ([]byte, error)) *CipherMock_GenerateIV_Call {
	_c.Call.Return(run)
	return _c
}

// NewAsymmetricCipherMock creates a new instance of AsymmetricCipherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAsymmetricCipherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AsymmetricCipherMock {
	mock := &AsymmetricCipherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AsymmetricCipherMock is an autogenerated mock type for the AsymmetricCipher type
type AsymmetricCipherMock struct {
	mock.Mock
}

type AsymmetricCipherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AsymmetricCipherMock) EXPECT() *AsymmetricCipherMock_Expecter {
	return &AsymmetricCipherMock_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type AsymmetricCipherMock
func (_mock *AsymmetricCipherMock) Decrypt(ciphertext string) (string, error) {
	ret := _mock.Called(ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(ciphertext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(ciphertext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(ciphertext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AsymmetricCipherMock_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type AsymmetricCipherMock_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext string
func (_e *AsymmetricCipherMock_Expecter) Decrypt(ciphertext interface{}) *AsymmetricCipherMock_Decrypt_Call {
	return &AsymmetricCipherMock_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext)}
}

func (_c *AsymmetricCipherMock_Decrypt_Call) Run(run func(ciphertext string)) *AsymmetricCipherMock_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AsymmetricCipherMock_Decrypt_Call) Return(s string, err error) *AsymmetricCipherMock_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AsymmetricCipherMock_Decrypt_Call) RunAndReturn(run func(ciphertext string) (string, error)) *AsymmetricCipherMock_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type AsymmetricCipherMock
func (_mock *AsymmetricCipherMock) Encrypt(plaintext string) (string, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AsymmetricCipherMock_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type AsymmetricCipherMock_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *AsymmetricCipherMock_Expecter) Encrypt(plaintext interface{}) *AsymmetricCipherMock_Encrypt_Call {
	return &AsymmetricCipherMock_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *AsymmetricCipherMock_Encrypt_Call) Run(run func(plaintext string)) *AsymmetricCipherMock_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AsymmetricCipherMock_Encrypt_Call) Return(s string, err error) *AsymmetricCipherMock_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AsymmetricCipherMock_Encrypt_Call) RunAndReturn(run func(plaintext string) (string, error)) *AsymmetricCipherMock_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type AsymmetricCipherMock
func (_mock *AsymmetricCipherMock) Sign(payload string) (string, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AsymmetricCipherMock_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type AsymmetricCipherMock_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - payload string
func (_e *AsymmetricCipherMock_Expecter) Sign(payload interface{}) *AsymmetricCipherMock_Sign_Call {
	return &AsymmetricCipherMock_Sign_Call{Call: _e.mock.On("Sign", payload)}
}

func (_c *AsymmetricCipherMock_Sign_Call) Run(run func(payload string)) *AsymmetricCipherMock_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AsymmetricCipherMock_Sign_Call) Return(s string, err error) *AsymmetricCipherMock_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AsymmetricCipherMock_Sign_Call) RunAndReturn(run func(payload string) (string, error)) *AsymmetricCipherMock_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type AsymmetricCipherMock
func (_mock *AsymmetricCipherMock) Verify(payload string, signature string) error {
	ret := _mock.Called(payload, signature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(payload, signature)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AsymmetricCipherMock_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type AsymmetricCipherMock_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - payload string
//   - signature string
func (_e *AsymmetricCipherMock_Expecter) Verify(payload interface{}, signature interface{}) *AsymmetricCipherMock_Verify_Call {
	return &AsymmetricCipherMock_Verify_Call{Call: _e.mock.On("Verify", payload, signature)}
}

func (_c *AsymmetricCipherMock_Verify_Call) Run(run func(payload string, signature string)) *AsymmetricCipherMock_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AsymmetricCipherMock_Verify_Call) Return(err error) *AsymmetricCipherMock_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AsymmetricCipherMock_Verify_Call) RunAndReturn(run func(payload string, signature string) error) *AsymmetricCipherMock_Verify_Call {
	_c.Call.Return(run)
	return _c
}
