#!/usr/bin/env python3
"""
generate.py — derive host adapters from the canonical policy.json.

The Claude Code adapter is the PreToolUse hook (hooks/hooks.json), which calls
policy_match.py at runtime — so there is nothing to "compile" for Claude beyond
asserting the wiring is intact. The Codex adapter is a static rules file
projected from policy.json.

NOTE ON THE CODEX PROJECTION: adapters/codex/execpolicy.rules is a deterministic,
documented projection of policy.json — one line per rule, grouped by bucket. It
is intended as a faithful, reviewable mapping; the exact on-disk syntax a given
Codex CLI version expects for its execpolicy may differ and need a thin adapter.
We do not claim version-specific loadability here — only determinism and fidelity
to policy.json (verify with: run twice, diff == empty).

Usage:
    python3 core/policy/generate.py          # write the projection, verify wiring
    python3 core/policy/generate.py --check  # verify only; non-zero if stale/broken
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[2]
POLICY_PATH = PLUGIN_ROOT / "core" / "policy" / "policy.json"
HOOKS_PATH = PLUGIN_ROOT / "hooks" / "hooks.json"
CODEX_RULES = PLUGIN_ROOT / "adapters" / "codex" / "execpolicy.rules"

HEADER = (
    "# GENERATED by core/policy/generate.py from core/policy/policy.json — DO NOT EDIT BY HAND.\n"
    "# Deterministic projection of the canonical command-safety policy. Evaluation\n"
    "# order is deny -> confirm -> allow -> default; deny wins. Regenerate after any\n"
    "# policy.json change. Exact Codex execpolicy syntax may need a per-version adapter.\n"
)


def render(policy: dict) -> str:
    lines = [HEADER, f"# default = {policy.get('default', 'ask')}\n"]
    for bucket in ("deny", "confirm", "allow"):
        lines.append(f"\n[{bucket}]\n")
        for rule in policy.get(bucket, []):
            reason = rule.get("reason", "")
            rid = rule.get("id", "")
            pat = rule.get("pattern", "")
            lines.append(f"rule {rid}: match=/{pat}/i action={bucket}")
            lines.append(f"  # {reason}\n" if reason else "\n")
    return "".join(lines)


def check_wiring() -> list[str]:
    problems: list[str] = []
    try:
        hooks = json.loads(HOOKS_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"hooks.json unreadable: {exc}"]
    pre = hooks.get("hooks", {}).get("PreToolUse", [])
    blob = json.dumps(pre)
    if '"matcher": "Bash"' not in blob and '"matcher":"Bash"' not in blob:
        problems.append("hooks.json PreToolUse does not match the Bash tool")
    if "policy_match.py" not in blob:
        problems.append("hooks.json PreToolUse does not invoke policy_match.py")
    if "${CLAUDE_PLUGIN_ROOT}" not in blob:
        problems.append("hooks.json command is not anchored to ${CLAUDE_PLUGIN_ROOT}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="generate host adapters from policy.json")
    parser.add_argument("--check", action="store_true", help="verify only; do not write")
    args = parser.parse_args(argv)

    policy = json.loads(POLICY_PATH.read_text(encoding="utf-8"))
    expected = render(policy)

    problems = check_wiring()
    if problems:
        print("FAIL: hook wiring check:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    if args.check:
        current = CODEX_RULES.read_text(encoding="utf-8") if CODEX_RULES.exists() else ""
        if current != expected:
            print("FAIL: adapters/codex/execpolicy.rules is stale; run generate.py.", file=sys.stderr)
            return 1
        print("OK: hook wiring intact and Codex projection up to date.")
        return 0

    CODEX_RULES.parent.mkdir(parents=True, exist_ok=True)
    CODEX_RULES.write_text(expected, encoding="utf-8")
    print(f"OK: wrote {CODEX_RULES.relative_to(PLUGIN_ROOT)} and verified hook wiring.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
