// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/b2c-e-commerce-platform/platform/backend/go-template/app/product/access"
)

// NewProductStorageMock creates a new instance of ProductStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductStorageMock {
	mock := &ProductStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductStorageMock is an autogenerated mock type for the ProductStorage type
type ProductStorageMock struct {
	mock.Mock
}

type ProductStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductStorageMock) EXPECT() *ProductStorageMock_Expecter {
	return &ProductStorageMock_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type ProductStorageMock
func (_mock *ProductStorageMock) CreateProduct(ctx context.Context, product access.Product) (access.Product, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 access.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Product) (access.Product, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Product) access.Product); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(access.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductStorageMock_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProductStorageMock_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product access.Product
func (_e *ProductStorageMock_Expecter) CreateProduct(ctx interface{}, product interface{}) *ProductStorageMock_CreateProduct_Call {
	return &ProductStorageMock_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *ProductStorageMock_CreateProduct_Call) Run(run func(ctx context.Context, product access.Product)) *ProductStorageMock_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.Product
		if args[1] != nil {
			arg1 = args[1].(access.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductStorageMock_CreateProduct_Call) Return(product1 access.Product, err error) *ProductStorageMock_CreateProduct_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *ProductStorageMock_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, product access.Product) (access.Product, error)) *ProductStorageMock_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type ProductStorageMock
func (_mock *ProductStorageMock) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductStorageMock_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type ProductStorageMock_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ProductStorageMock_Expecter) DeleteProduct(ctx interface{}, id interface{}) *ProductStorageMock_DeleteProduct_Call {
	return &ProductStorageMock_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *ProductStorageMock_DeleteProduct_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ProductStorageMock_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductStorageMock_DeleteProduct_Call) Return(err error) *ProductStorageMock_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductStorageMock_DeleteProduct_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *ProductStorageMock_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type ProductStorageMock
func (_mock *ProductStorageMock) GetProductByID(ctx context.Context, id uuid.UUID) (access.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 access.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (access.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) access.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(access.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductStorageMock_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type ProductStorageMock_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ProductStorageMock_Expecter) GetProductByID(ctx interface{}, id interface{}) *ProductStorageMock_GetProductByID_Call {
	return &ProductStorageMock_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *ProductStorageMock_GetProductByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ProductStorageMock_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductStorageMock_GetProductByID_Call) Return(product access.Product, err error) *ProductStorageMock_GetProductByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductStorageMock_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (access.Product, error)) *ProductStorageMock_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function for the type ProductStorageMock
func (_mock *ProductStorageMock) ListProducts(ctx context.Context, organizationID uuid.UUID) ([]access.Product, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []access.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]access.Product, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []access.Product); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]access.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductStorageMock_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type ProductStorageMock_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID uuid.UUID
func (_e *ProductStorageMock_Expecter) ListProducts(ctx interface{}, organizationID interface{}) *ProductStorageMock_ListProducts_Call {
	return &ProductStorageMock_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, organizationID)}
}

func (_c *ProductStorageMock_ListProducts_Call) Run(run func(ctx context.Context, organizationID uuid.UUID)) *ProductStorageMock_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductStorageMock_ListProducts_Call) Return(products []access.Product, err error) *ProductStorageMock_ListProducts_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *ProductStorageMock_ListProducts_Call) RunAndReturn(run func(ctx context.Context, organizationID uuid.UUID) ([]access.Product, error)) *ProductStorageMock_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function for the type ProductStorageMock
func (_mock *ProductStorageMock) UpdateProduct(ctx context.Context, product access.Product) (access.Product, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 access.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Product) (access.Product, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Product) access.Product); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(access.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductStorageMock_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type ProductStorageMock_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product access.Product
func (_e *ProductStorageMock_Expecter) UpdateProduct(ctx interface{}, product interface{}) *ProductStorageMock_UpdateProduct_Call {
	return &ProductStorageMock_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, product)}
}

func (_c *ProductStorageMock_UpdateProduct_Call) Run(run func(ctx context.Context, product access.Product)) *ProductStorageMock_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.Product
		if args[1] != nil {
			arg1 = args[1].(access.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductStorageMock_UpdateProduct_Call) Return(product1 access.Product, err error) *ProductStorageMock_UpdateProduct_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *ProductStorageMock_UpdateProduct_Call) RunAndReturn(run func(ctx context.Context, product access.Product) (access.Product, error)) *ProductStorageMock_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}
