// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package zip_mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/b2c-e-commerce-platform/platform/backend/common/zip"
)

// NewZipperMock creates a new instance of ZipperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewZipperMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ZipperMock {
	mock := &ZipperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ZipperMock is an autogenerated mock type for the Zipper type
type ZipperMock struct {
	mock.Mock
}

type ZipperMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ZipperMock) EXPECT() *ZipperMock_Expecter {
	return &ZipperMock_Expecter{mock: &_m.Mock}
}

// CompressStream provides a mock function for the type ZipperMock
func (_mock *ZipperMock) CompressStream(files []zip.ArchiveFile, out io.Writer) error {
	ret := _mock.Called(files, out)

	if len(ret) == 0 {
		panic("no return value specified for CompressStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]zip.ArchiveFile, io.Writer) error); ok {
		r0 = returnFunc(files, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ZipperMock_CompressStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompressStream'
type ZipperMock_CompressStream_Call struct {
	*mock.Call
}

// CompressStream is a helper method to define mock.On call
//   - files []zip.ArchiveFile
//   - out io.Writer
func (_e *ZipperMock_Expecter) CompressStream(files interface{}, out interface{}) *ZipperMock_CompressStream_Call {
	return &ZipperMock_CompressStream_Call{Call: _e.mock.On("CompressStream", files, out)}
}

func (_c *ZipperMock_CompressStream_Call) Run(run func(files []zip.ArchiveFile, out io.Writer)) *ZipperMock_CompressStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []zip.ArchiveFile
		if args[0] != nil {
			arg0 = args[0].([]zip.ArchiveFile)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ZipperMock_CompressStream_Call) Return(err error) *ZipperMock_CompressStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ZipperMock_CompressStream_Call) RunAndReturn(run func(files []zip.ArchiveFile, out io.Writer) error) *ZipperMock_CompressStream_Call {
	_c.Call.Return(run)
	return _c
}

// UnzipSecure provides a mock function for the type ZipperMock
func (_mock *ZipperMock) UnzipSecure(in io.ReaderAt, size int64, destDir string) error {
	ret := _mock.Called(in, size, destDir)

	if len(ret) == 0 {
		panic("no return value specified for UnzipSecure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.ReaderAt, int64, string) error); ok {
		r0 = returnFunc(in, size, destDir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ZipperMock_UnzipSecure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnzipSecure'
type ZipperMock_UnzipSecure_Call struct {
	*mock.Call
}

// UnzipSecure is a helper method to define mock.On call
//   - in io.ReaderAt
//   - size int64
//   - destDir string
func (_e *ZipperMock_Expecter) UnzipSecure(in interface{}, size interface{}, destDir interface{}) *ZipperMock_UnzipSecure_Call {
	return &ZipperMock_UnzipSecure_Call{Call: _e.mock.On("UnzipSecure", in, size, destDir)}
}

func (_c *ZipperMock_UnzipSecure_Call) Run(run func(in io.ReaderAt, size int64, destDir string)) *ZipperMock_UnzipSecure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.ReaderAt
		if args[0] != nil {
			arg0 = args[0].(io.ReaderAt)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ZipperMock_UnzipSecure_Call) Return(err error) *ZipperMock_UnzipSecure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ZipperMock_UnzipSecure_Call) RunAndReturn(run func(in io.ReaderAt, size int64, destDir string) error) *ZipperMock_UnzipSecure_Call {
	_c.Call.Return(run)
	return _c
}
